# fonts
awesome: &awesome SauceCodePro Nerd Font:style=solid:pixelsize=18
awesome_brands: &awesome_brands SauceCodePro Nerd Font:pixelsize=20

std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}

# This is THE bar configuration
bar:
  height: 26
  location: top
  spacing: 5
  margin: 5

  # Default font
  font: SauceCodePro Nerd Font:pixelsize=18

  foreground: ffffffff
  background: 111111cc

  border:
    width: 1
    color: 999999cc
    margin: 5
    top-margin: 0

  left:
    - script:
        path: /home/josema/.config/yambar/dwl-tags.sh
        args: [1]
        anchors:
          - occupied: &occupied {foreground: f1ffffff}
          - focused: &focused {foreground: a47de9ff}
          - default: &default {foreground: 4c566aff}
        content:
          - map:
              margin: 4
              tag: tag_0_occupied
              values:
                true:
                  map:
                    tag: tag_0_focused
                    values:
                      true: {string: {text: "{tag_0}", <<: *focused}}
                      false: {string: {text: "{tag_0}", <<: *occupied}}
                false:
                  map:
                    tag: tag_0_focused
                    values:
                      true: {string: {text: "{tag_0}", <<: *focused}}
                      false: {string: {text: "{tag_0}", <<: *default}}
          - map:
              margin: 4
              tag: tag_1_occupied
              values:
                true:
                  map:
                    tag: tag_1_focused
                    values:
                      true: {string: {text: "{tag_1}", <<: *focused}}
                      false: {string: {text: "{tag_1}", <<: *occupied}}
                false:
                  map:
                    tag: tag_1_focused
                    values:
                      true: {string: {text: "{tag_1}", <<: *focused}}
                      false: {string: {text: "{tag_1}", <<: *default}}
          - map:
              margin: 4
              tag: tag_2_occupied
              values:
                true:
                  map:
                    tag: tag_2_focused
                    values:
                      true: {string: {text: "{tag_2}", <<: *focused}}
                      false: {string: {text: "{tag_2}", <<: *occupied}}
                false:
                  map:
                    tag: tag_2_focused
                    values:
                      true: {string: {text: "{tag_2}", <<: *focused}}
                      false: {string: {text: "{tag_2}", <<: *default}}
          - map:
              margin: 4
              tag: tag_3_occupied
              values:
                true:
                  map:
                    tag: tag_3_focused
                    values:
                      true: {string: {text: "{tag_3}", <<: *focused}}
                      false: {string: {text: "{tag_3}", <<: *occupied}}
                false:
                  map:
                    tag: tag_3_focused
                    values:
                      true: {string: {text: "{tag_3}", <<: *focused}}
                      false: {string: {text: "{tag_3}", <<: *default}}
          - map:
              margin: 4
              tag: tag_4_occupied
              values:
                true:
                  map:
                    tag: tag_4_focused
                    values:
                      true: {string: {text: "{tag_4}", <<: *focused}}
                      false: {string: {text: "{tag_4}", <<: *occupied}}
                false:
                  map:
                    tag: tag_4_focused
                    values:
                      true: {string: {text: "{tag_4}", <<: *focused}}
                      false: {string: {text: "{tag_4}", <<: *default}}
          - map:
              margin: 4
              tag: tag_5_occupied
              values:
                true:
                  map:
                    tag: tag_5_focused
                    values:
                      true: {string: {text: "{tag_5}", <<: *focused}}
                      false: {string: {text: "{tag_5}", <<: *occupied}}
                false:
                  map:
                    tag: tag_5_focused
                    values:
                      true: {string: {text: "{tag_5}", <<: *focused}}
                      false: {string: {text: "{tag_5}", <<: *default}}
          - map:
              margin: 4
              tag: tag_6_occupied
              values:
                true:
                  map:
                    tag: tag_6_focused
                    values:
                      true: {string: {text: "{tag_6}", <<: *focused}}
                      false: {string: {text: "{tag_6}", <<: *occupied}}
                false:
                  map:
                    tag: tag_6_focused
                    values:
                      true: {string: {text: "{tag_6}", <<: *focused}}
                      false: {string: {text: "{tag_6}", <<: *default}}
          - map:
              margin: 4
              tag: tag_7_occupied
              values:
                true:
                  map:
                    tag: tag_7_focused
                    values:
                      true: {string: {text: "{tag_7}", <<: *focused}}
                      false: {string: {text: "{tag_7}", <<: *occupied}}
                false:
                  map:
                    tag: tag_7_focused
                    values:
                      true: {string: {text: "{tag_7}", <<: *focused}}
                      false: {string: {text: "{tag_7}", <<: *default}}
          - map:
              margin: 4
              tag: tag_8_occupied
              values:
                true:
                  map:
                    tag: tag_8_focused
                    values:
                      true: {string: {text: "{tag_8}", <<: *focused}}
                      false: {string: {text: "{tag_8}", <<: *occupied}}
                false:
                  map:
                    tag: tag_8_focused
                    values:
                      true: {string: {text: "{tag_8}", <<: *focused}}
                      false: {string: {text: "{tag_8}", <<: *default}}
          - list:
              spacing: 3
              items:
                  #- string: {text: "{layout}"}
                  - string: {text: "{title}", max: 55}

  right:
    - removables:
        anchors:
          drive: &drive { text: 禍, font: *awesome_brands}
          optical: &optical {text: " ", font: *awesome_brands}
        spacing: 5
        content:
          map:
            tag: mounted
            values:
              false:
                map:
                  tag: optical
                  on-click: udisksctl mount -b {device}
                  values:
                    false: [{string: *drive}, {string: {text: "{label}"}}]
                    true: [{string: *optical}, {string: {text: "{label}"}}]
              true:
                map:
                  tag: optical
                  on-click: udisksctl unmount -b {device}
                  values:
                    false:
                      - string: {<<: *drive, deco: *std_underline}
                      - string: {text: "{label}"}
                    true:
                      - string: {<<: *optical, deco: *std_underline}
                      - string: {text: "{label}"}

    - network:
        name: eno1
        content:
          map:
            tag: carrier
            values:
              false: {empty: {}}
              true:
                map:
                  tag: state
                  default: {string: {text: " ", font: *awesome_brands, foreground: ffffff66}}
                  values:
                    up:
                      map:
                        tag: ipv4
                        default: {string: {text: " ", font: *awesome_brands}}
                        values:
                          "": {string: {text: " ", font: *awesome_brands, foreground: ffffff66}}
    - network:
        name: wlo1
        content:
          map:
            tag: state
            default: {string: {text: " ", font: *awesome, foreground: ffffff66}}
            values:
              down: {string: {text: " ", font: *awesome, foreground: ff0000ff}}
              up:
                map:
                  tag: ipv4
                  default: {string: {text: " ", font: *awesome}}
                  values:
                    "": {string: {text: " ", font: *awesome, foreground: ffffff66}}
    - alsa:
        card: hw:PCH
        mixer: Master
        content:
          map:
            on-click: /bin/sh -c "amixer -q sset Speaker unmute && amixer -q sset Headphone unmute && amixer -q sset Master toggle"
            tag: muted
            values:
              true: {string: {text: 婢, font: *awesome_brands, foreground: ffffff66}}
              false:
                ramp:
                  tag: volume
                  items:
                    - string: {text: , font: *awesome_brands}
                    - string: {text: 奔, font: *awesome_brands}
                    - string: {text: 墳, font: *awesome_brands}

    - battery:
        name: BAT0
        poll-interval: 30
        content:
          map:
            tag: state
            values:
              discharging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: "   ", foreground: ff0000ff, font: *awesome}
                      - string: {text: "   ", foreground: ffa600ff, font: *awesome}
                      - string: {text: "   ", foreground: ffa600ff, font: *awesome}
                      - string: {text: "   ", font: *awesome}
                      - string: {text: "   ", font: *awesome}
                      - string: {text: "   ", font: *awesome}
                      - string: {text: "   ", font: *awesome}
                      - string: {text: "   ", font: *awesome}
                      - string: {text: "   ", font: *awesome}
                      - string: {text: "   ", foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}%"}
              charging:
                - string: {text: "  ", foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}%"}
              full:
                - string: {text: "   ", foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}% full"}
    - clock:
        time-format: "%H:%M"
        content:
          - string: {text: "  ", font: *awesome_brands}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: " ", font: *awesome_brands}
          - string: {text: "{time}"}
    - label:
        content:
          string:
            on-click: shutdown now
            text: " "
            font: *awesome_brands