#! /bin/sh

# keys daemon
sxhkd &

# status bar
polybar bar1 &

# Avoid x cursor
xsetroot -cursor_name left_ptr &

# bspwm config==========================================
bspc monitor -d 1 2 3 4

bspc config border_width            2
bspc config window_gap              8

bspc config click_to_focus          true
bspc config focus_follows_pointer   true

bspc config pointer_action1         move
bspc config pointer_action2         resize_corner

bspc config history_aware_focus     false

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config normal_border_color     "#4c566a"
bspc config active_border_color     "#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color     "#dd2727"

# hide polybar when full screen
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

# floating rules=========================================
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a zoom state=floating